# set -g default-terminal "xterm-256color"
# set -g default-terminal "screen-256color"
# set -ga terminal-overrides ",*256col*:Tc"

# set -ga terminal-overrides ',xterm-256color:Tc'
# set -g default-terminal "tmux-256color"
# set -as terminal-overrides ',xterm*:sitm=\E[3m'

set -g mouse on

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

# Center the window list
# set -g status-justify centre

# Maximize and restore a pane
#unbind Up bind Up new-window -d -n tmp \; swap-pane -s tmp.1 \; select-window -t tmp
#unbind Down
#bind Down last-window \; swap-pane -s tmp.1 \; kill-window -t tmp

#set -g pane-active-border-style fg=colour208,bg=default

# if-shell "test -f $HOME/.tmuxline_snapshot" "source $HOME/.tmuxline_snapshot"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-net-speed'
set -g @plugin 'samoshkin/tmux-plugin-sysstat'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'egel/tmux-gruvbox'

run -b '~/.tmux/plugins/tpm/tpm'



set -g default-terminal "screen-256color"
set -as terminal-overrides ",*256col*:Tc"
set -g default-terminal "xterm"


set-window-option -g mode-keys vi
